Update requirements.txt
kossiitkgp/kwoc-stats-api pull request #16
Opened 2020-10-19 16:24 UTC by j-tesla

Add the `requests` module

fixes kossiitkgp#15

2020-10-19 17:50 UTC, rakaar requested changes

2020-10-19 17:50 UTC, rakaar commented on requirements.txt
> +requirements
it should be requests right?

2020-10-19 18:03 UTC, j-tesla commented on requirements.txt
> +requirements
extremely sorry! my bad!

2020-10-19 18:11 UTC, rakaar commented
Hey @j-tesla 
I tried forking and added the PAT too, but there were no new commits in my fork. You can check [here](https://github.com/rakaar/kwoc-stats-api/tree/j-tesla-stats-workflow-patch)

I even tried changing the time interval to for every 2 mins, u can check it [here](https://github.com/rakaar/kwoc-stats-api/commit/548b76221968a7311d9d5b433dbeae2fc39149f2)

What am I missing?
Can u please help me out

2020-10-19 18:15 UTC, rakaar requested changes
sorry for telling it late
but for packages that are utilized in production, it is better to have version number
actually it is good to have a version for all packages. But I didn't notice it, my bad!

Please add the latest version of requests - as [here](https://pypi.org/project/requests/)
if u are free, u can add the version for other packages too. It would a great help

2020-10-20 02:23 UTC, rakaar commented
thank you so much @j-tesla  for the patience in  adding version numbers for other requirements too!

2020-10-20 02:23 UTC, merged